include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Avoid print statements
    avoid_print: true
    
    # Code quality
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    prefer_final_fields: true
    prefer_final_locals: true
    
    # Unused imports
    unused_imports: true
    unused_local_variable: true
    
    # Widget best practices
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
    
    # Naming conventions
    non_constant_identifier_names: true
    constant_identifier_names: true
    
    # Code organization
    always_declare_return_types: true
    avoid_empty_else: true
    avoid_returning_null_for_future: true
    avoid_unnecessary_containers: true
    avoid_relative_lib_imports: true
    
    # Complexity
    cyclomatic_complexity: true
    
    # Best practices
    avoid_dynamic_calls: true
    avoid_function_literals_in_foreach_calls: true
    avoid_redundant_argument_values: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    cancel_subscriptions: true
    close_sinks: true
    no_duplicate_case_values: true

analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"
  errors:
    invalid_annotation_target: ignore
    todo: ignore
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true
